version: "3"
services:
  web:
    build: ./ed-client
    depends_on:
        - server
    ports:
      - "3000:3000"
  db:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
  data:
    build: ./data
    depends_on:
        - db
  server:
    build: ./ed-server
    depends_on:
        - data
    ports:
      - "4000:4000"
